WHENEVER SQLERROR CONTINUE NONE;
DROP TABLE book_subjects;
DROP TABLE subjects;
DROP TABLE bs;

WHENEVER SQLERROR EXIT SQL.SQLCODE;
CREATE TABLE subjects (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE book_subjects (
  book_id INTEGER REFERENCES books (id),
  subject_id INTEGER REFERENCES subjects (id),
  PRIMARY KEY (book_id, subject_id)
);

INSERT INTO subjects (name) 
  SELECT DISTINCT(subjects) FROM 
    (SELECT trim(COLUMN_VALUE) subjects 
    FROM books, xmltable(('"' || REPLACE(subjects, '|', '","') || '"')));

CREATE TABLE bs AS (
  SELECT id AS book_id, trim(COLUMN_VALUE) subjects 
  FROM books, xmltable(('"' || REPLACE(subjects, '|', '","') || '"')));

INSERT INTO book_subjects
  SELECT bs.book_id, subjects.id FROM bs INNER JOIN subjects ON bs.subjects = subjects.name;

DROP TABLE bs;

ALTER TABLE books DROP COLUMN subjects;

EXIT;
