WHENEVER SQLERROR CONTINUE NONE;
DROP TABLE publishers CASCADE CONSTRAINTS;

WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE TABLE publishers (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO publishers (name)
  SELECT DISTINCT(publisher) FROM books;

ALTER TABLE books
  ADD publisher_id NUMBER REFERENCES publishers(id);

UPDATE books 
  SET publisher_id = (SELECT id FROM publishers 
                      WHERE publishers.name = books.publisher)
  WHERE publisher_id IS NULL;

ALTER TABLE books
  DROP COLUMN publisher;

EXIT;
