WHENEVER SQLERROR CONTINUE NONE;
DROP TABLE collections;
WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE TABLE collections (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  checkout_duration INTERVAL DAY TO SECOND NOT NULL
);

INSERT INTO collections (id, name, checkout_duration)
VALUES (1, 'Standard', INTERVAL '14' DAY);
INSERT INTO collections (id, name, checkout_duration)
VALUES (2, 'Special', INTERVAL '5' DAY);

ALTER TABLE books ADD collection_id NUMBER REFERENCES collections(id);

UPDATE books SET collection_id = 1;
UPDATE books SET collection_id = 2 
  WHERE id IN (SELECT id FROM books ORDER BY dbms_random.value FETCH FIRST 50 ROWS ONLY);

EXIT;
