WHENEVER SQLERROR CONTINUE NONE;
DROP TABLE book_authors;
DROP TABLE authors;
DROP TABLE ba;

WHENEVER SQLERROR EXIT SQL.SQLCODE;
CREATE TABLE authors (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE book_authors (
  book_id INTEGER REFERENCES books (id),
  author_id INTEGER REFERENCES authors (id),
  PRIMARY KEY (book_id, author_id)
);

INSERT INTO authors (name) 
  SELECT DISTINCT(author) FROM 
    (SELECT trim(COLUMN_VALUE) author
    FROM books, xmltable(('"' || REPLACE(author, '|', '","') || '"')));

CREATE TABLE ba AS (
  SELECT id AS book_id, trim(COLUMN_VALUE) author 
  FROM books, xmltable(('"' || REPLACE(author, '|', '","') || '"')));

INSERT INTO book_authors
  SELECT ba.book_id, authors.id FROM ba INNER JOIN authors ON ba.author = authors.name;

DROP TABLE ba;

ALTER TABLE books DROP COLUMN author;

EXIT;
